[default.databases.rusqlite]
url = "file:rusqlite?mode=memory&cache=shared"

[default.databases.sqlx]
url = "db/sqlx/db.sqlite"

[default.databases.diesel]
url = "db/diesel/db.sqlite"
timeout = 10

[default.databases.diesel_mysql]
url = "mysql://example-user:my_cool_secret@172.19.0.2:3306/rover"

[global]
address = "0.0.0.0"
port = 4455

[development]
address = "0.0.0.0"
port = 4455