[features]
reverse_proxy_authentication = true

[reverse_proxy_authentication.config]
header = "host"

[frontend.metadata]
instance_hostname = "guard.motionfans.com"
alias = "Rover"
public_description = "A device management tool."
image = "https://images.unsplash.com/photo-1565799557186-1abfed8a31e5?q=80&w=3087&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
motd_banner1 = "ACME is down, they're experiencing issues, use a backup authentication method."
background_colour = "#0b040e"
domain_placeholder="example.com"
username_placeholder="username"
acess_denied_header=""

[database.mysql]
username = "example-user"
password_env = "example_user_mysql_password"
hostname = "172.19.0.2"
port = 3306
database = "guard"

[sql.tables]
user = "accounts"
device = "devices"
magiclink = "magiclinks"

[smtp]
host="smtp.sendgrid.net"
port=587
username="apikey"
from_alias="MotionFans Guard"
from_header="noreply@paperplane.motionfans.com"
reply_to_address="noreply@paperplane.motionfans.com"
password_env="smtp_password"

[captcha.hcaptcha.login_page]
site_key = ""
hcaptcha_secret_env = "login_page_hcaptcha_secret"
size = "normal"

[authentication_methods.email]
active = true
method_type = "email"
handoff = "https://example.com/handoff"
applied_policies = ["staff_only"]
login_page = "https://example.com/failure"
validation_endpoint = "https://example.com/success"
should_create_new_users = true
ratelimit = 5
ratelimit_cooldown = 200
user_info_reference_type = "email"
user_info_reference_key = "email"

[policies.staff_only]
active = true
action = "allow"
property = "email"
ends_with = "@motionfans.com"
and = ["email_verified"]

[policies.email_verified]
active = true
action = "allow"
property = "email_verified"
is = ["true"]

[hostname.anythingyouwant]
active = true
host = "127.0.0.1"
applied_policies = ["staff_only"]
authentication_methods = ["email"]
multistep_authentication_methods = false